// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DATABASE_ID: string;
	CLOUDFLARE_D1_API_TOKEN: string;
	CLOUDFLARE_D1_ACCOUNT_ID: string;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	DB: D1Database;
}
